config/routes.rb
Rails.application.routes.draw do
  root 'weather#index'
  post 'weather/show', to: 'weather#show'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
  end

  def show
    @address = params[:address]
    @zipcode = params[:zipcode]
    @city = params[:city]
    @state = params[:state]

    if @zipcode.present?
      @weather = WeatherService::Client.current_by_zipcode(@zipcode)
    elsif @city.present? && @state.present?
      @weather = WeatherService::Client.current_by_city_state(@city, @state)
    else
      render_error
    end

    respond_to do |format|
      format.html
      format.js
    end
  rescue WeatherService::Client::Error
    render_error
  end

  private

  def render_error
    @error = 'Unable to retrieve a weather forecast at this time.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&libraries=places&callback=initAutocomplete" async defer></script>
  </head>

  <body>
    <div class="heading">Weather Reporter</div>
    <%= yield %>
  </body>
</html>

app/views/weather/_weather_info.html.erb
<% if @weather %>
  <div class="weather-info">
    <h1>Current Weather for <%= @address %></h1>
    <div class="temperature">
      <h2>Current Temperature: <%= @weather.temperature %>°F</h2>
    </div>
    <div class="temperature-range">
      <h3>Today's High: <%= @weather.max_temperature %>°F</h3>
      <h3>Today's Low: <%= @weather.min_temperature %>°F</h3>
    </div>
    <% if @weather.cached? %>
      <div class="cache-notice">
        This is a cached weather report and may be slightly out of date.
      </div>
    <% end %>
  </div>
<% else %>
  <div class="weather-info">
    <h1><%= @error %></h1>
  </div>
<% end %>

app/views/weather/index.html.erb
<%= form_with(url: weather_show_path, method: :post, local: false, html: { class: "address-form" }) do |form| %>
  <div class="form-section">
    <%= form.label :address, "Search by City or Zipcode:" %>
    <%= text_field_tag :address, nil, id: 'address-input', autocomplete: 'off' %>
  </div>
  
  <%= form.hidden_field :city, id: 'city-field', class: "hidden" %>
  <%= form.hidden_field :state, id: 'state-field', class: "hidden" %>
  <%= form.hidden_field :zipcode, id: 'zipcode-field', class: "hidden" %>
  <%= form.submit "Check Weather", id: "submit-button", class: "btn", disabled: true %>
<% end %>
<div id="weather_result"></div>

app/views/weather/show.html.erb
<%= render 'weather_info' %>

app/views/weather/show.js.erb
document.getElementById('weather_result').innerHTML = '<%= j render("weather_info") %>';